# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160921_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
    ]
